# Generated by Django 5.2.6 on 2025-09-20 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SessionLap',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('race_id', models.IntegerField(verbose_name='Race Id')),
                ('session_type', models.CharField(
                    max_length=100, verbose_name='Session Type')),
                ('driver_pk', models.IntegerField(verbose_name='Driver Pk')),
                ('lap_time', models.TimeField(verbose_name='Lap Time')),
                ('lap_number', models.IntegerField(verbose_name='Lap Number')),
                ('pit_in_time', models.TimeField(verbose_name='Pit In Time')),
                ('pit_out_time', models.TimeField(verbose_name='Pit Out Time')),
                ('sector1_time', models.TimeField(verbose_name='Sector 1 Time')),
                ('sector2_time', models.TimeField(verbose_name='Sector 2 Time')),
                ('sector3_time', models.TimeField(verbose_name='Sector 3 Time')),
                ('speed_i1', models.FloatField(verbose_name='Speed trap 1')),
                ('speed_i2', models.FloatField(verbose_name='Speed Trap 2')),
                ('speed_fl', models.FloatField(verbose_name='Speed Finish Line')),
                ('speed_st', models.FloatField(verbose_name='Speed at Finish Line')),
                ('personal_best', models.BooleanField(
                    default=False, verbose_name='Personal Best')),
                ('compound', models.CharField(
                    max_length=50, verbose_name='Compound')),
                ('tyre_life', models.IntegerField(verbose_name='Tyre Life')),
                ('team', models.CharField(max_length=50, verbose_name='Team Name')),
                ('track_status', models.CharField(
                    max_length=50, verbose_name='Track Status')),
                ('position', models.FloatField(verbose_name='Track Position')),
                ('deleted', models.BooleanField(
                    default=False, verbose_name='Lap Deleted')),
                ('deleted_reason', models.CharField(
                    max_length=100, verbose_name='Deleted Reason')),
            ],
        ),
    ]
