# Generated by Django 5.2.6 on 2025-09-21 18:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('live_data', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LapTelemetry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_stamp', models.DateTimeField(verbose_name='Time Stamp')),
                ('rpm', models.FloatField(verbose_name='Engine RPM')),
                ('speed', models.FloatField(verbose_name='Car Speed')),
                ('gear', models.IntegerField(verbose_name='Transmission Gear')),
                ('throttle', models.FloatField(verbose_name='Throttle')),
                ('brake', models.BooleanField(default=False, verbose_name='Brake')),
                ('drs', models.IntegerField(verbose_name='DRS status')),
                ('session_time', models.TimeField(verbose_name='Session Time')),
                ('lap', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='laps', to='live_data.sessionlap')),
            ],
        ),
    ]
