# Generated by Django 5.2.6 on 2025-09-21 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('live_data', '0002_laptelemetry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sessionlap',
            name='driver_pk',
            field=models.CharField(max_length=50, verbose_name='Driver Pk'),
        ),
    ]
