# Generated by Django 5.2.6 on 2025-09-21 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('live_data', '0003_driver_pk_char_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laptelemetry',
            name='drs',
            field=models.IntegerField(null=True, verbose_name='DRS status'),
        ),
        migrations.AlterField(
            model_name='laptelemetry',
            name='gear',
            field=models.IntegerField(null=True, verbose_name='Transmission Gear'),
        ),
        migrations.AlterField(
            model_name='laptelemetry',
            name='rpm',
            field=models.FloatField(null=True, verbose_name='Engine RPM'),
        ),
        migrations.AlterField(
            model_name='laptelemetry',
            name='session_time',
            field=models.TimeField(null=True, verbose_name='Session Time'),
        ),
        migrations.AlterField(
            model_name='laptelemetry',
            name='speed',
            field=models.FloatField(null=True, verbose_name='Car Speed'),
        ),
        migrations.AlterField(
            model_name='laptelemetry',
            name='throttle',
            field=models.FloatField(null=True, verbose_name='Throttle'),
        ),
        migrations.AlterField(
            model_name='sessionlap',
            name='compound',
            field=models.CharField(max_length=50, null=True, verbose_name='Compound'),
        ),
        migrations.AlterField(
            model_name='sessionlap',
            name='deleted',
            field=models.BooleanField(default=False, null=True, verbose_name='Lap Deleted'),
        ),
        migrations.AlterField(
            model_name='sessionlap',
            name='deleted_reason',
            field=models.CharField(max_length=100, null=True, verbose_name='Deleted Reason'),
        ),
        migrations.AlterField(
            model_name='sessionlap',
            name='pit_in_time',
            field=models.TimeField(null=True, verbose_name='Pit In Time'),
        ),
        migrations.AlterField(
            model_name='sessionlap',
            name='pit_out_time',
            field=models.TimeField(null=True, verbose_name='Pit Out Time'),
        ),
        migrations.AlterField(
            model_name='sessionlap',
            name='position',
            field=models.FloatField(null=True, verbose_name='Track Position'),
        ),
        migrations.AlterField(
            model_name='sessionlap',
            name='sector1_time',
            field=models.TimeField(null=True, verbose_name='Sector 1 Time'),
        ),
        migrations.AlterField(
            model_name='sessionlap',
            name='sector2_time',
            field=models.TimeField(null=True, verbose_name='Sector 2 Time'),
        ),
        migrations.AlterField(
            model_name='sessionlap',
            name='sector3_time',
            field=models.TimeField(null=True, verbose_name='Sector 3 Time'),
        ),
        migrations.AlterField(
            model_name='sessionlap',
            name='speed_fl',
            field=models.FloatField(null=True, verbose_name='Speed Finish Line'),
        ),
        migrations.AlterField(
            model_name='sessionlap',
            name='speed_i1',
            field=models.FloatField(null=True, verbose_name='Speed trap 1'),
        ),
        migrations.AlterField(
            model_name='sessionlap',
            name='speed_i2',
            field=models.FloatField(null=True, verbose_name='Speed Trap 2'),
        ),
        migrations.AlterField(
            model_name='sessionlap',
            name='speed_st',
            field=models.FloatField(null=True, verbose_name='Speed at Finish Line'),
        ),
        migrations.AlterField(
            model_name='sessionlap',
            name='team',
            field=models.CharField(max_length=50, null=True, verbose_name='Team Name'),
        ),
        migrations.AlterField(
            model_name='sessionlap',
            name='track_status',
            field=models.CharField(max_length=50, null=True, verbose_name='Track Status'),
        ),
        migrations.AlterField(
            model_name='sessionlap',
            name='tyre_life',
            field=models.IntegerField(null=True, verbose_name='Tyre Life'),
        ),
    ]
