# Generated by Django 5.2.6 on 2025-09-21 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('live_data', '0004_null_value_fix'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sessionlap',
            name='lap_time',
            field=models.TimeField(null=True, verbose_name='Lap Time'),
        ),
    ]
