# Generated by Django 5.2.6 on 2025-09-27 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('live_data', '0005_lap_time_null_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sessionlap',
            name='personal_best',
            field=models.BooleanField(default=False, null=True, verbose_name='Personal Best'),
        ),
    ]
